---
- name: Configure public EC2 instance with Docker
  hosts: public_instances
  roles:
    - docker

- name: Configure private EC2 instance with nodejs
  hosts: private_instances
  roles: 
    - nodejs

